spring.application.name=api
spring.datasource.url=${LOG_SENTINEL_DB_URL:jdbc:postgresql://localhost:5432/log_sentinel}
spring.datasource.username=${LOG_SENTINEL_DB_USER:log_sentinel}
spring.datasource.password=${LOG_SENTINEL_DB_PASSWORD:log_sentinel}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
